services:
    db:
        image: surrealdb/surrealdb:1.0.0-beta.8
        command: "start -b ${SURREAL_ADDRESS}:${SURREAL_PORT_CONTAINER} -u ${SURREAL_ROOT_USER} -p ${SURREAL_ROOT_PASS} memory"
        environment:
            SURREAL_PORT_CONTAINER: ${SURREAL_PORT_CONTAINER}
            SURREAL_ROOT_USER: ${SURREAL_ROOT_USER}
            SURREAL_ROOT_PASS: ${SURREAL_ROOT_PASS}
        ports:
            - ${SURREAL_PORT_HOST}:${SURREAL_PORT_CONTAINER}
        # healthcheck:
        #     test: curl -f http://localhost:${SURREAL_PORT_CONTAINER}/health
        #     interval: 10s
        #     retries: 1
        #     start_period: 10s
        #     timeout: 10s
        networks:
            - app

    client:
        build: ./client
        environment:
            PORT: ${CLIENT_PORT_CONTAINER}
        volumes:
            - ./client:/usr/src/app
        ports:
            - ${CLIENT_PORT_HOST}:${CLIENT_PORT_CONTAINER}
        networks:
            - app

    server:
        build: ./server
        environment:
            PORT: ${SERVER_PORT_CONTAINER}
            DB_URL: ${DB_URL}
            DB_USER: ${SURREAL_ROOT_USER}
            DB_PASS: ${SURREAL_ROOT_PASS}
        volumes:
            - ./server:/usr/src/app
            # - /mnt/c/watch-test:/watch
            # - /mnt/c/stable-diffusion-webui-automatic/outputs/txt2img-images:/watch
            - /home/zach/horde/outputs/txt2img-samples/samples:/watch
        ports:
            - ${SERVER_PORT_HOST}:${SERVER_PORT_CONTAINER}
        # depends_on:
        #     db:
        #         condition: service_healthy
        networks:
            - app

networks:
    app:
        driver: bridge
